//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileService45.SMSAgent {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMSAgent.SMSAgentWSSoap")]
    public interface SMSAgentWSSoap {
        
        // CODEGEN: Generating message contract since element name mtseq from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMT", ReplyAction="*")]
        MobileService45.SMSAgent.SendMTResponse SendMT(MobileService45.SMSAgent.SendMTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMT", ReplyAction="*")]
        System.Threading.Tasks.Task<MobileService45.SMSAgent.SendMTResponse> SendMTAsync(MobileService45.SMSAgent.SendMTRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMT", Namespace="http://tempuri.org/", Order=0)]
        public MobileService45.SMSAgent.SendMTRequestBody Body;
        
        public SendMTRequest() {
        }
        
        public SendMTRequest(MobileService45.SMSAgent.SendMTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mtseq;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string moid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string moseq;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string src;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string dest;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string cmdcode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string msgbody;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string msgtype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string msgtitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string mttotalseg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string mtseqref;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string cpid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string reqtime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string procresult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string opid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string password;
        
        public SendMTRequestBody() {
        }
        
        public SendMTRequestBody(
                    string mtseq, 
                    string moid, 
                    string moseq, 
                    string src, 
                    string dest, 
                    string cmdcode, 
                    string msgbody, 
                    string msgtype, 
                    string msgtitle, 
                    string mttotalseg, 
                    string mtseqref, 
                    string cpid, 
                    string reqtime, 
                    string procresult, 
                    string opid, 
                    string username, 
                    string password) {
            this.mtseq = mtseq;
            this.moid = moid;
            this.moseq = moseq;
            this.src = src;
            this.dest = dest;
            this.cmdcode = cmdcode;
            this.msgbody = msgbody;
            this.msgtype = msgtype;
            this.msgtitle = msgtitle;
            this.mttotalseg = mttotalseg;
            this.mtseqref = mtseqref;
            this.cpid = cpid;
            this.reqtime = reqtime;
            this.procresult = procresult;
            this.opid = opid;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMTResponse", Namespace="http://tempuri.org/", Order=0)]
        public MobileService45.SMSAgent.SendMTResponseBody Body;
        
        public SendMTResponse() {
        }
        
        public SendMTResponse(MobileService45.SMSAgent.SendMTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendMTResult;
        
        public SendMTResponseBody() {
        }
        
        public SendMTResponseBody(int SendMTResult) {
            this.SendMTResult = SendMTResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SMSAgentWSSoapChannel : MobileService45.SMSAgent.SMSAgentWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSAgentWSSoapClient : System.ServiceModel.ClientBase<MobileService45.SMSAgent.SMSAgentWSSoap>, MobileService45.SMSAgent.SMSAgentWSSoap {
        
        public SMSAgentWSSoapClient() {
        }
        
        public SMSAgentWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSAgentWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSAgentWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSAgentWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MobileService45.SMSAgent.SendMTResponse MobileService45.SMSAgent.SMSAgentWSSoap.SendMT(MobileService45.SMSAgent.SendMTRequest request) {
            return base.Channel.SendMT(request);
        }
        
        public int SendMT(
                    string mtseq, 
                    string moid, 
                    string moseq, 
                    string src, 
                    string dest, 
                    string cmdcode, 
                    string msgbody, 
                    string msgtype, 
                    string msgtitle, 
                    string mttotalseg, 
                    string mtseqref, 
                    string cpid, 
                    string reqtime, 
                    string procresult, 
                    string opid, 
                    string username, 
                    string password) {
            MobileService45.SMSAgent.SendMTRequest inValue = new MobileService45.SMSAgent.SendMTRequest();
            inValue.Body = new MobileService45.SMSAgent.SendMTRequestBody();
            inValue.Body.mtseq = mtseq;
            inValue.Body.moid = moid;
            inValue.Body.moseq = moseq;
            inValue.Body.src = src;
            inValue.Body.dest = dest;
            inValue.Body.cmdcode = cmdcode;
            inValue.Body.msgbody = msgbody;
            inValue.Body.msgtype = msgtype;
            inValue.Body.msgtitle = msgtitle;
            inValue.Body.mttotalseg = mttotalseg;
            inValue.Body.mtseqref = mtseqref;
            inValue.Body.cpid = cpid;
            inValue.Body.reqtime = reqtime;
            inValue.Body.procresult = procresult;
            inValue.Body.opid = opid;
            inValue.Body.username = username;
            inValue.Body.password = password;
            MobileService45.SMSAgent.SendMTResponse retVal = ((MobileService45.SMSAgent.SMSAgentWSSoap)(this)).SendMT(inValue);
            return retVal.Body.SendMTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MobileService45.SMSAgent.SendMTResponse> MobileService45.SMSAgent.SMSAgentWSSoap.SendMTAsync(MobileService45.SMSAgent.SendMTRequest request) {
            return base.Channel.SendMTAsync(request);
        }
        
        public System.Threading.Tasks.Task<MobileService45.SMSAgent.SendMTResponse> SendMTAsync(
                    string mtseq, 
                    string moid, 
                    string moseq, 
                    string src, 
                    string dest, 
                    string cmdcode, 
                    string msgbody, 
                    string msgtype, 
                    string msgtitle, 
                    string mttotalseg, 
                    string mtseqref, 
                    string cpid, 
                    string reqtime, 
                    string procresult, 
                    string opid, 
                    string username, 
                    string password) {
            MobileService45.SMSAgent.SendMTRequest inValue = new MobileService45.SMSAgent.SendMTRequest();
            inValue.Body = new MobileService45.SMSAgent.SendMTRequestBody();
            inValue.Body.mtseq = mtseq;
            inValue.Body.moid = moid;
            inValue.Body.moseq = moseq;
            inValue.Body.src = src;
            inValue.Body.dest = dest;
            inValue.Body.cmdcode = cmdcode;
            inValue.Body.msgbody = msgbody;
            inValue.Body.msgtype = msgtype;
            inValue.Body.msgtitle = msgtitle;
            inValue.Body.mttotalseg = mttotalseg;
            inValue.Body.mtseqref = mtseqref;
            inValue.Body.cpid = cpid;
            inValue.Body.reqtime = reqtime;
            inValue.Body.procresult = procresult;
            inValue.Body.opid = opid;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((MobileService45.SMSAgent.SMSAgentWSSoap)(this)).SendMTAsync(inValue);
        }
    }
}
